### ISSUE TITLE
Harmonize `div` and `mul` between constants 

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-dao/morpho-utils#42]
`div` and `mul` between constants are optimized by the compiler and does not cost more gas than using constants. Perhaps we should come back to `div(MAX_UINT256, HALF_PERCENTAGE_FACTOR)`?

**Comment by QGarchery** [comment]
If we want to use the same notation everywhere (I'm not sure we do), then I think we should use the `div` and `mul` instead yes.
First because writing something like `MAX_UINT256_DIVIDED_BY_HALF_PERCENTAGE_FACTOR = 0xd1b71758e219652bd3c36113404ea4a8c154c985f06f694467381d7dbf487` looks bad and is error prone. And also because this way we don't have to know those variable names, trust that they represent what we expect them to represent, and replace their occurences everywhere.

**Comment by MerlinEgalite** [comment]
PR has been closed, closing this issue as well as not planned
